//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.Celebration.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Apps.Celebration.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anniversary.
        /// </summary>
        internal static string AnniversaryEventTypeName {
            get {
                return ResourceManager.GetString("AnniversaryEventTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        internal static string BirthdayEventTypeName {
            get {
                return ResourceManager.GetString("BirthdayEventTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditButtonTitle {
            get {
                return ResourceManager.GetString("EditButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is celebrating {1} with the team..
        /// </summary>
        internal static string EventCardTitle {
            get {
                return ResourceManager.GetString("EventCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I couldn&apos;t find this event..
        /// </summary>
        internal static string EventDoesNotExistMessage {
            get {
                return ResourceManager.GetString("EventDoesNotExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event occurrence has already passed..
        /// </summary>
        internal static string EventPassedMessage {
            get {
                return ResourceManager.GetString("EventPassedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is celebrating {1} with the team..
        /// </summary>
        internal static string EventPreviewCardHeader {
            get {
                return ResourceManager.GetString("EventPreviewCardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {0}, you have an upcoming event in the next 3 days. If you take no action, I will post this celebration..
        /// </summary>
        internal static string EventPreviewMessageText {
            get {
                return ResourceManager.GetString("EventPreviewMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like you joined a new team. Would you like to share your events in {0} as well?.
        /// </summary>
        internal static string EventShareMessage {
            get {
                return ResourceManager.GetString("EventShareMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, I&apos;ll skip &quot;{0}&quot; this year and won&apos;t share it with your teams..
        /// </summary>
        internal static string EventSkippedMessage {
            get {
                return ResourceManager.GetString("EventSkippedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started.
        /// </summary>
        internal static string GetStartedButtonText {
            get {
                return ResourceManager.GetString("GetStartedButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, if you change your mind you can share the events from the Events tab..
        /// </summary>
        internal static string IgnoreEventShare {
            get {
                return ResourceManager.GetString("IgnoreEventShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop the presses! Today {0} and {1}. That&apos;s a lot of merrymaking for one day—pace yourselves!.
        /// </summary>
        internal static string MultipleEventsMessage {
            get {
                return ResourceManager.GetString("MultipleEventsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re celebrating multiple events today!.
        /// </summary>
        internal static string MultipleEventsSummary {
            get {
                return ResourceManager.GetString("MultipleEventsSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, thanks.
        /// </summary>
        internal static string NoThanksButtonTitle {
            get {
                return ResourceManager.GetString("NoThanksButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string OtherEventTypeName {
            get {
                return ResourceManager.GetString("OtherEventTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string ShareButtonTitle {
            get {
                return ResourceManager.GetString("ShareButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some error occurred while share your events with team. Please try again..
        /// </summary>
        internal static string ShareWithTeamGenericError {
            get {
                return ResourceManager.GetString("ShareWithTeamGenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are no longer a member of {0}..
        /// </summary>
        internal static string ShareWithTeamNotAMemberError {
            get {
                return ResourceManager.GetString("ShareWithTeamNotAMemberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Someone uninstalled me from {0}, I can no longer share these events there..
        /// </summary>
        internal static string ShareWithTeamsNotInstalledError {
            get {
                return ResourceManager.GetString("ShareWithTeamsNotInstalledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I’ve set those events to be shared with the team when they occur..
        /// </summary>
        internal static string ShareWithTeamSuccessMessage {
            get {
                return ResourceManager.GetString("ShareWithTeamSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;at&gt;{0}&lt;/at&gt; is celebrating {1}.
        /// </summary>
        internal static string SingleEventMessage {
            get {
                return ResourceManager.GetString("SingleEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string SkipButtonTitle {
            get {
                return ResourceManager.GetString("SkipButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the event is either already passed, or has been changed since this card was sent..
        /// </summary>
        internal static string SkippedStaleEventMessage {
            get {
                return ResourceManager.GetString("SkippedStaleEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a tour.
        /// </summary>
        internal static string TakeATourButtonText {
            get {
                return ResourceManager.GetString("TakeATourButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour.
        /// </summary>
        internal static string TourTaskModuleTitle {
            get {
                return ResourceManager.GetString("TourTaskModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m the Celebrations bot. {0} installed me in {1}. I’m here to help everyone celebrate birthdays, anniversaries, and anything else you tell me about..
        /// </summary>
        internal static string WelcomeMessageForTeam {
            get {
                return ResourceManager.GetString("WelcomeMessageForTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi!.
        /// </summary>
        internal static string WelcomeMessageForTeamTitle {
            get {
                return ResourceManager.GetString("WelcomeMessageForTeamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi!.
        /// </summary>
        internal static string WelcomeMessageForUserTitle {
            get {
                return ResourceManager.GetString("WelcomeMessageForUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for installing me. I’m ready to help you celebrate special events with your team. Currently you don’t have me in any of your teams.
        /// </summary>
        internal static string WelcomeMessagePart1 {
            get {
                return ResourceManager.GetString("WelcomeMessagePart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click get started to start adding your own events..
        /// </summary>
        internal static string WelcomeMessagePart2 {
            get {
                return ResourceManager.GetString("WelcomeMessagePart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then install me in a team so that I can help you and your team members remember and share their events..
        /// </summary>
        internal static string WelcomeMessagePart3 {
            get {
                return ResourceManager.GetString("WelcomeMessagePart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I’m ready to help you celebrate special events with your team. Click get started to add your own events..
        /// </summary>
        internal static string WelcomeMessagePart4 {
            get {
                return ResourceManager.GetString("WelcomeMessagePart4", resourceCulture);
            }
        }
    }
}
